name: survival_analysis
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - lifelines
  - scikit-learn
  - causalml
  - notebook
  - ipywidgets
  - pip
